### ISSUE TITLE
Build failed with an exception

### ISSUE THREAD

**Issue by Z6P0** [ja2375/add_2_calendar#141]
After I upgraded Flutter, my project doesn't compile anymore.
Here is the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':add_2_calendar:compileDebugJavaWithJavac'.
> error: invalid source release: 17

```

I tried to change the Java version but without success.
I have the latest add_2_calendar version 2.2.5.

**Comment by Devangplutustec** [comment]
update the android studio to latest and project level it working for me

**Comment by Z6P0** [comment]
I use the latest VS Code with latest Flutter and it's not working.

**Comment by BrunoLuigiOO** [comment]
Having the same issue. Upgrading the Gradle version didn't work.

build.gradle
```
dependencies {
        classpath 'com.android.tools.build:gradle:7.3.0'
        ...
}
```

gradle-wrapper.properties
```
...
distributionUrl=https\://services.gradle.org/distributions/gradle-7.5-all.zip
```

**Comment by jabele** [comment]
I'm experiencing the same error. I was able to remove it completely and successfully compile but there was no version of it from 2.1.3 to 2.2.5 that worked with my environment.

**Comment by kikashy** [comment]
Same here

```
Execution failed for task ':add_2_calendar:compileReleaseJavaWithJavac'.
> error: invalid source release: 17
```
add_2_calendar: ^2.2.3

Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (9 days ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

**Comment by kikashy** [comment]
I am using AppCenter to build, this worked.
Basically, the env variable for JAVA_HOME needs to be updated to JAVA_HOME_17_X64

https://stackoverflow.com/questions/76854810/appcenter-ms-android-gradle-plugin-requires-java-17

**Comment by ankitkrmishra123** [comment]
> After I upgraded Flutter, my project doesn't compile anymore. Here is the error:
> 
> ```
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':add_2_calendar:compileDebugJavaWithJavac'.
> > error: invalid source release: 17
> ```
> 
> I tried to change the Java version but without success. I have the latest add_2_calendar version 2.2.5.

got same issue - today only

**Comment by adrianvintu** [comment]
Same error, cannot build via GitHub Actions

**Comment by dJani97** [comment]
I'm getting this in Codemagic as well. I tried changing the JDK to 17 in a pre-build script, but it doesn't seem to help:

export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"

**Comment by kherel** [comment]
downgrade to version 2.2.4

**Comment by abdullahalamodi** [comment]
the same error here

**Comment by abdullahalamodi** [comment]
I fixed it.
you can use this pull request ref until it is merged
 
add_2_calendar:
    git:
      url: https://github.com/ja2375/add_2_calendar.git
      ref: 493d902e998a397bfd7468cc5874dd38e7d1f067

**Comment by diegogarciar** [comment]
Just created 3.0.0, let me know if you still have issues

**Comment by Z6P0** [comment]
Sorry but I still have the problem with 3.0.0. It only works if I downgrade to 2.2.4.

**Comment by diegogarciar** [comment]
alright, 3.0.1 published!

**Comment by Thelm76** [comment]
it works again for me now 😉 thanks for the merge @diegogarciar
